export const AppRoutes = {
    HOME: '/',
    SEARCH: '/search',
    CATEGORY: '/:category',
    CATEGORY_WILDCARD: '/:category/*',
    SUB_CATEGORY: ':subCategory',
    RECIPE: '/:category/:subCategory/:id',
    THE_JUICIEST: '/the-juiciest',
    NOT_FOUND: '/not-found',
    SIGN_IN: '/signin',
    SIGN_UP: '/signup',
    VERIFICATION: '/verification',
    RECOVERY: '/signin/recovery',
    CREATE_RECIPE: '/new-recipe',
    EDIT: '/edit-recipe',
    EDIT_RECIPE: '/edit-recipe/:category/:subCategory/:id',
} as const;
