export const DATA_TEST_IDS = {
    APP_LOADER: 'app-loader',
    NAV: 'nav',
    FOOTER: 'footer',
    BREADCRUMBS: 'breadcrumbs',
    CLOSE_ICON: 'close-icon',
    HAMBURGER_ICON: 'hamburger-icon',
    HEADER: 'header',
    LOGIN_INPUT: 'login-input',
    PASSWORD_INPUT: 'password-input',
    CONFIRM_PASSWORD_INPUT: 'confirm-password-input',
    RESET_CREDENTIALS_MODAL: 'reset-credentials-modal',
    SUBMIT_BUTTON: 'submit-button',
    SEND_EMAIL_MODAL: 'send-email-modal',
    REPEAT_BUTTON: 'repeat-button',
    SIGN_IN_ERROR_MODAL: 'sign-in-error-modal',
    SIGN_UP_SUCCESS_MODAL: 'sign-up-success-modal',
    VERIFICATION_CODE_MODAL: 'verification-code-modal',
    EMAIL_VERIFICATION_FAILED_MODAL: 'email-verification-failed-modal',
    INCREMENT_STEPPER: 'increment-stepper',
    DECREMENT_STEPPER: 'decrement-stepper',
    FILTER_DRAWER: 'filter-drawer',
    CLOSE_FILTER_DRAWER: 'close-filter-drawer',
    ALLERGENS_SWITCHER_FILTER: 'allergens-switcher-filter',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    FILTER_TAG: 'filter-tag',
    CLEAR_FILTER_BUTTON: 'clear-filter-button',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    LOADER_SEARCH_BLOCK: 'loader-search-block',
    FILTER_BUTTON: 'filter-button',
    SEARCH_INPUT: 'search-input',
    SEARCH_BUTTON: 'search-button',
    ALLERGENS_SWITCHER: 'allergens-switcher',
    CAROUSEL_BACK: 'carousel-back',
    CAROUSEL_FORWARD: 'carousel-forward',
    CAROUSEL: 'carousel',
    CLOSE_BUTTON: 'close-button',
    JUICIEST_LINK: 'juiciest-link',
    JUICIEST_LINK_MOBILE: 'juiciest-link-mobile',
    PASSWORD_VISIBILITY_BUTTON: 'password-visibility-button',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT_BUTTON: 'close-alert-button',
    ERROR_PAGE_GO_HOME: 'error-page-go-home',
    LOAD_MORE_BUTTON: 'load-more-button',
    SIGN_IN_FORM: 'sign-in-form',
    SIGN_UP_FORM: 'sign-up-form',
    FORGOT_PASSWORD: 'forgot-password',
    SIGN_UP_PROGRESS: 'sign-up-progress',
    FIRST_NAME_INPUT: 'first-name-input',
    LAST_NAME_INPUT: 'last-name-input',
    EMAIL_INPUT: 'email-input',
    RECIPE_IMAGE_BLOCK: 'recipe-image-block',
    RECIPE_IMAGE_INPUT: 'recipe-image-block-input-file',
    RECIPE_PREVIEW_IMAGE: 'recipe-image-block-preview-image',
    RECIPE_IMAGE_MODAL: 'recipe-image-modal',
    RECIPE_IMAGE_MODAL_IMAGE_BLOCK: 'recipe-image-modal-image-block',
    RECIPE_IMAGE_MODAL_PREVIEW_IMAGE: 'recipe-image-modal-preview-image',
    RECIPE_CATEGORIES: 'recipe-categories',
    RECIPE_TITLE: 'recipe-title',
    RECIPE_DESCRIPTION: 'recipe-description',
    RECIPE_TIME: 'recipe-time',
    RECIPE_PORTIONS: 'recipe-portions',
    RECIPE_SAVE_DRAFT_BUTTON: 'recipe-save-draft-button',
    RECIPE_PUBLISH_RECIPE_BUTTON: 'recipe-publish-recipe-button',
    RECIPE_ADD_INGREDIENTS_BUTTON: 'recipe-ingredients-add-ingredients',
    RECIPE_PREVENTIVE_MODAL: 'recipe-preventive-modal',
    RECIPE_DELETE_BUTTON: 'recipe-delete-button',
    HEADER_LOGO: 'header-logo',
    ADD_RECIPE_BUTTON: 'add-recipe-button',
    RECIPE_FORM: 'recipe-form',
    MAIN_PAGE_BLOGS_BOX: 'main-page-blogs-box',
    MAIN_PAGE_BLOGS_BUTTON: 'main-page-blogs-button',
    MAIN_PAGE_BLOGS_GRID: 'main-page-blogs-grid',

    // Blog cards
    BLOG_CARD: 'blogs-card',
    BLOG_CARD_NAME: 'blogs-card-name',
    BLOG_CARD_LOGIN: 'blogs-card-login',
    BLOG_CARD_NOTES_TEXT: 'blogs-card-notes-text',
    BLOG_CARD_NEW_RECIPES_BADGE: 'blogs-card-new-recipes-badge',
    BLOG_CARD_RECIPES_BUTTON: 'blogs-card-recipes-button',
    BLOG_CARD_NOTES_BUTTON: 'blogs-card-notes-button',

    // Favorites section
    BLOG_FAVORITES_BOX: 'blogs-favorites-box',
    BLOG_FAVORITES_GRID: 'blogs-favorites-grid',

    // Others section
    BLOG_OTHERS_BOX: 'blogs-others-box',
    BLOG_OTHERS_GRID: 'blogs-others-grid',
    BLOG_OTHERS_BUTTON: 'blogs-others-button',

    // Blogger page
    BLOGGER_USER_INFO_NAME: 'blogger-user-info-name',
    BLOGGER_USER_INFO_LOGIN: 'blogger-user-info-login',
    BLOGGER_FOLLOWERS_COUNT: 'blogger-followers-count',
    BLOGGER_FOLLOWERS_BOOKMARKS: 'blogger-followers-bookmarks',
    BLOGGER_USER_NOTES_COUNT: 'blogger-user-notes-count',
    BLOGGER_USER_NOTES_GRID: 'blogger-user-notes-grid',
    BLOGGER_USER_NOTES_BUTTON: 'blogger-user-notes-button',

    // Notes
    NOTES_CARD_DATE: 'notes-card-date',
    NOTES_CARD_TEXT: 'notes-card-text',

    // Other blogs
    BLOGGER_USER_OTHER_BLOGS_BUTTON: 'blogger-user-other-blogs-button',
    BLOGGER_USER_OTHER_BLOGS_GRID: 'blogger-user-other-blogs-grid',

    // Subscription
    BLOG_TOGGLE_SUBSCRIBE: 'blog-toggle-subscribe',
    BLOG_TOGGLE_UNSUBSCRIBE: 'blog-toggle-unsubscribe',

    // Breadcrumbs
    BLOGGER_USER_BREADCRUMB_NAME: 'blogger-user-breadcrumb-name',
    BLOGGER_USER_BREADCRUMB_SECTION: 'blogger-user-breadcrumb-section',

    // Error
    ERROR_NOTIFICATION_TITLE: 'error-notification-title',
    ERROR_NOTIFICATION_DESCRIPTION: 'error-notification-description',

    // Other
    BLOG_TOOLTIP: 'blog-tooltip',
    MOBILE_LOADER: 'mobile-loader',
};
