export const Z_INDEX_CONFIG = {
    HEADER: 40,
    MODAL: 50,
    DRAWER: 50,
    GLOBAL_LOADER: 50,
    NAVBAR_MENU: 40,
    NAVBAR_OVERLAY: 30,
    FOOTER: 20,
    SELECT_MENU: 10,
    FORM_SUBMIT_BTNS: 32,
    SLIDER_BTNS: 10,
    TOAST: 51,
} as const;
