export const Z_INDEX_CONFIG = {
    HEADER: 31,
    MODAL: 40,
    DRAWER: 40,
    GLOBAL_LOADER: 50,
    NAVBAR_MENU: 31,
    NAVBAR_OVERLAY: 30,
    FOOTER: 20,
    SELECT_MENU: 10,
    FORM_SUBMIT_BTNS: 0,
    SLIDER_BTNS: 10,
    TOAST: 41,
} as const;
