export enum ApiEndpoints {
    RECIPES = '/recipe',
    RECIPE_CATEGORY = '/recipe/category/',
    RECIPE_BY_ID = '/recipe/',
    CATEGORY_BY_ID = '/category/',
    CATEGORIES = '/category',
    AUTH = '/auth/login',
    SIGN_UP = '/auth/signup',
    REFRESH_TOKEN = '/auth/refresh',
    CHECK_AUTH = '/auth/check-auth',
    FORGOT_PASSWORD = '/auth/forgot-password',
    VERIFY_OTP = '/auth/verify-otp',
    RESET_PASSWORD = '/auth/reset-password',
    MEASURE_UNITS = '/measure-units',
    CREATE_RECIPE_DRAFT = '/recipe/draft',
    GET_RECIPES_BY_USER_ID = '/recipe/user/',
    LIKE_UNLIKE_RECIPE = '/like',
    SAVE_REMOVE_FROM_BOOKMARKS = '/bookmark',
    FILE_UPLOAD = '/file/upload',
    BLOGGERS = '/bloggers',
    USER_TOGGLE_SUBSCRIPTION = '/users/toggle-subscription',
}
