export enum EndpointNames {
    GET_LATEST_RECIPES = 'getLatestRecipes',
    GET_POPULAR_RECIPES = 'getPopularRecipes',
    GET_RECIPE_BY_ID = 'getRecipeById',
    GET_RECIPES_BY_CATEGORY = 'getRecipesByCategory',
    GET_CATEGORIES = 'getCategories',
    GET_CATEGORY_BY_ID = 'getCategoryById',
    SEARCH_RECIPES = 'searchRecipes',
    SIGN_IN = 'signIn',
    SIGN_UP = 'signUp',
    CHECK_AUTH = 'checkAuth',
    FORGOT_PASSWORD = 'forgotPassword',
    VERIFY_OTP = 'verifyOtp',
    RESET_PASSWORD = 'resetPassword',
}
