export enum EndpointNames {
    GET_LATEST_RECIPES = 'getLatestRecipes',
    GET_POPULAR_RECIPES = 'getPopularRecipes',
    GET_RECIPE_BY_ID = 'getRecipeById',
    GET_RECIPES_BY_CATEGORY = 'getRecipesByCategory',
    GET_CATEGORIES = 'getCategories',
    GET_CATEGORY_BY_ID = 'getCategoryById',
    SEARCH_RECIPES = 'searchRecipes',
    SIGN_IN = 'signIn',
    SIGN_UP = 'signUp',
    CHECK_AUTH = 'checkAuth',
    FORGOT_PASSWORD = 'forgotPassword',
    VERIFY_CODE = 'verifyCode',
    RESET_PASSWORD = 'resetPassword',
    REFRESH_TOKEN = 'refreshToken',
    MEASURE_UNITS = 'measureUnits',
    UPDATE_RECIPE = 'updateRecipe',
    DELETE_RECIPE = 'deleteRecipe',
    CREATE_RECIPE = 'createRecipe',
    CREATE_RECIPE_DRAFT = 'createRecipeDraft',
    GET_RECIPES_BY_USER_ID = 'getRecipesByUserId',
    LIKE_UNLIKE_RECIPE = 'likeUnlikeRecipe',
    SAVE_REMOVE_FROM_BOOKMARKS = 'saveRemoveFromBookmarks',
    FILE_UPLOAD = 'fileUpload',
}
